### PR TITLE
[WIP] Feature/refactor ESNEXT

### PR DESCRIPTION
**Pull request by luigiplr**
Proposed PR will bump code base up to latest ES6 guidelines and introduce some ES7 syntactic sugars through `babel-preset-stage-0`. (babel compiles to `/dist`)

In addition to the following I have moved all 'core' module code into `/src` and any leftovers for demo'ing/testing etc into `/test`, Both these directories have also been added to `.npmignore` to prevent them from being included in production use.

Finally I plan to harness [Webpack](https://webpack.github.io) & [webpack-dev-server](https://www.npmjs.com/package/webpack-dev-server) for the compiling of `demo.html` & its subsequent assets, this should allow for seamless testing & prototyping.
## PR Checklist!
- [x] Babel compile task
- [ ] Brought all code up to ES6 spec w/ some ES7 class sugars.
- [x] Added pre-publish task to create ES5 compatible module
- [x] Restructured directory's for cleaner project
- [x] Cleaned up `package.json`
- [x] Added `.npmignore` & ENHANCED `.gitignore`
- [ ] Added Swag™
- [ ] Create testing w/ webpack & hot-reloading via webpack-dev-server

### CODE REVIEW

**Comment by jaruba** [comment]
oh shit..

giphy

**Comment by SchizoDuckie** [comment]
Uurgh...

**Comment by jaruba** [comment]
@SchizoDuckie The Gods of Torrents have Descended Upon You

**Comment by SchizoDuckie** [comment]
The Gods Of Torrents and the New Testament of ESNEXT

**Pull request merged**
